class Model {
    constructor() {
        this.cardsList = [
            {
                picture: "assets/images/mainPage/Animals1.jpg",
                title: "Animal 1",
                cards: [
                    {
                        picture: "assets/images/animals1/bear.png",
                        title: "Bear",
                        translate:"Медведь",
                        audio:"assets/audio/bear.mp3",
                        category:"Animal 1",
                        correct:0,
                        mistakes:0,
                        training:0,

                    },
                    {
                        picture: "assets/images/animals1/bird.jpg",
                        title: "Bird",
                        translate:"Птица",
                        audio:"assets/audio/bird.mp3",
                        category:"Animal 1",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/animals1/cat.png",
                        title: "Cat",
                        translate:"Кот",
                        audio:"assets/audio/cat.mp3",
                        category:"Animal 1",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/animals1/deer.webp",
                        title: "Deer",
                        translate:"Олень",
                        audio:"assets/audio/deer.mp3",
                        category:"Animal 1",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/animals1/dog.jpg",
                        title: "Dog",
                        translate:"Собака",
                        audio:"assets/audio/dog.mp3",
                        category:"Animal 1",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/animals1/fox.jpg",
                        title: "Fox",
                        translate:"Лиса",
                        audio:"assets/audio/fox.mp3",
                        category:"Animal 1",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/animals1/frog.jpg",
                        title: "Frog",
                        translate:"Лягушка",
                        audio:"assets/audio/frog.mp3",
                        category:"Animal 1",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/animals1/lion.jpg",
                        title: "Lion",
                        translate:"Лев",
                        audio:"assets/audio/lion.mp3",
                        category:"Animal 1",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                ]
            },
            {
                picture: "assets/images/mainPage/Animals2.webp",
                title: "Animal 2",
                cards: [
                    {
                        picture: "assets/images/animals2/donkey.png",
                        title: "Donkey",
                        translate:"Ослик",
                        audio:"assets/audio/donkey.mp3",
                        category:"Animal 2",
                        correct:0,
                        mistakes:0,
                        training:0,

                    },
                    {
                        picture: "assets/images/animals2/hog.png",
                        title: "Hog",
                        translate:"Кабанчик",
                        audio:"assets/audio/hog.mp3",
                        category:"Animal 2",
                        correct:0,
                        mistakes:0,
                        training:0,

                    },
                    {
                        picture: "assets/images/animals2/kangaroo.jpg",
                        title: "Kangaroo",
                        translate:"Кенгуру",
                        audio:"assets/audio/kangaroo.mp3",
                        category:"Animal 2",
                        correct:0,
                        mistakes:0,
                        training:0,

                    },
                    {
                        picture: "assets/images/animals2/mouse.jpg",
                        title: "Mouse",
                        translate:"Мышка",
                        audio:"assets/audio/mouse.mp3",
                        category:"Animal 2",
                        correct:0,
                        mistakes:0,
                        training:0,

                    },
                    {
                        picture: "assets/images/animals2/pig.jpg",
                        title: "Pig",
                        translate:"Свинка",
                        audio:"assets/audio/pig.mp3",
                        category:"Animal 2",
                        correct:0,
                        mistakes:0,
                        training:0,

                    },
                    {
                        picture: "assets/images/animals2/rabbit.jpg",
                        title: "Rabbit",
                        translate:"Кролик",
                        audio:"assets/audio/rabbit.mp3",
                        category:"Animal 2",
                        correct:0,
                        mistakes:0,
                        training:0,

                    },
                    {
                        picture: "assets/images/animals2/tiger.webp",
                        title: "Tiger",
                        translate:"Тигр",
                        audio:"assets/audio/tiger.mp3",
                        category:"Animal 2",
                        correct:0,
                        mistakes:0,
                        training:0,

                    },
                    {
                        picture: "assets/images/animals2/белка.jpg",
                        title: "Squirrel",
                        translate:"Белка",
                        audio:"assets/audio/squirrel.mp3",
                        category:"Animal 2",
                        correct:0,
                        mistakes:0,
                        training:0,

                    },
                ]
            },
            {
                picture: "assets/images/mainPage/book.jpg",
                title: "Films",
                cards: [
                    {
                        picture: "assets/images/films/comedy.png",
                        title: "Comedy",
                        translate:"Комедия",
                        audio:"assets/audio/comedy.mp3",
                        category:"Films",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/films/pinokio.webp",
                        title: "Fairy tale",
                        translate:"Сказка",
                        audio:"assets/audio/fairy tale.mp3",
                        category:"Films",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/films/hisctorical.jpg",
                        title: "Historical",
                        translate:"Историческое кино",
                        audio:"assets/audio/historical.mp3",
                        category:"Films",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/films/horror.jpg",
                        title: "Horror",
                        translate:"Ужасы",
                        audio:"assets/audio/horror.mp3",
                        category:"Films",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/films/romantika.jpg",
                        title: "Romance",
                        translate:"Романтика",
                        audio:"assets/audio/romance.mp3",
                        category:"Films",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/films/westrn.jpg",
                        title: "Western",
                        translate:"Вестерн",
                        audio:"assets/audio/western.mp3",
                        category:"Films",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/films/драма.jpg",
                        title: "Drama",
                        translate:"Драма",
                        audio:"assets/audio/drama.mp3",
                        category:"Films",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/films/боевик.jpg",
                        title: "Action",
                        translate:"Боевик",
                        audio:"assets/audio/action.mp3",
                        category:"Films",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },

                ],
            },
            {
                picture: "assets/images/mainPage/clothes.jpg",
                title: "Clothes",
                cards: [
                    {
                        picture: "assets/images/clothes/boots.jpg",
                        title: "Boots",
                        translate:"Ботинки",
                        audio:"assets/audio/boots.mp3",
                        category:"Clothes",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/clothes/dress.jpg",
                        title: "Dress",
                        translate:"Платье",
                        audio:"assets/audio/dress.mp3",
                        category:"Clothes",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/clothes/jeans.jpg",
                        title: "Jeans",
                        translate:"Джинсы",
                        audio:"assets/audio/jeans.mp3",
                        category:"Clothes",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/clothes/shirt.jpg",
                        title: "Shirt",
                        translate:"Рубашка",
                        audio:"assets/audio/shirt.mp3",
                        category:"Clothes",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/clothes/snakers.jpg",
                        title: "Sneakers",
                        translate:"Кроссовки",
                        audio:"assets/audio/sneakers.mp3",
                        category:"Clothes",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/clothes/socks.jpg",
                        title: "Socks",
                        translate:"Носки",
                        audio:"assets/audio/socks.mp3",
                        category:"Clothes",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/clothes/suit.jpg",
                        title: "Skirt",
                        translate:"Юбка",
                        audio:"assets/audio/skirt.mp3",
                        category:"Clothes",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/clothes/t-shirt.jpg",
                        title: "T-shirt",
                        translate:"Майка",
                        audio:"assets/audio/t-shirt.mp3",
                        category:"Clothes",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                ],
            },
            {
                picture: "assets/images/mainPage/food.jpg",
                title: "Food",
                cards: [
                    {
                        picture: "assets/images/food1/cake.png",
                        title: "Cake",
                        translate:"Пироженное",
                        audio:"assets/audio/cake.mp3",
                        category:"Food",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/food1/chicken.webp",
                        title: "Chicken",
                        translate:"Курица",
                        audio:"assets/audio/chicken.mp3",
                        category:"Food",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/food1/cookies.jpg",
                        title: "Сookies",
                        translate:"Печеньки",
                        audio:"assets/audio/cookies.mp3",
                        category:"Food",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/food1/donut.png",
                        title: "Donut",
                        translate:"Пончик",
                        audio:"assets/audio/donut.mp3",
                        category:"Food",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/food1/burger-removebg-preview.png",
                        title: "Burger",
                        translate:"Бургер",
                        audio:"assets/audio/burger.mp3",
                        category:"Food",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/food1/ice-cream.jpg",
                        title: "Ice cream",
                        translate:"Мороженное",
                        audio:"assets/audio/ice-cream.mp3",
                        category:"Food",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/food1/pankakes.png",
                        title: "Pancakes",
                        translate:"Блинчики",
                        audio:"assets/audio/panckakes.mp3",
                        category:"Food",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/food1/soup.webp",
                        title: "Soup",
                        translate:"Суп",
                        audio:"assets/audio/soup.mp3",
                        category:"Food",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                ],
            },
            {
                picture: "assets/images/mainPage/food2.jpg",
                title: "Food 2",
                cards: [
                    {
                        picture: "assets/images/food2/avocado.webp",
                        title: "Avocado",
                        translate:"Авокадо",
                        audio:"assets/audio/avocado.mp3",
                        category:"Food 2",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/food2/coffee.jpg",
                        title: "Coffee",
                        translate:"Кофе",
                        audio:"assets/audio/coffee.mp3",
                        category:"Food 2",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/food2/ham.jpg",
                        title: "Ham",
                        translate:"Ветчина",
                        audio:"assets/audio/ham.mp3",
                        category:"Food 2",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/food2/hot-dog.png",
                        title: "Hot-dog",
                        translate:"Хот-дог",
                        audio:"assets/audio/hot-dog.mp3",
                        category:"Food 2",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/food2/pizza.jpg",
                        title: "Pizza",
                        translate:"Пицца",
                        audio:"assets/audio/pizza.mp3",
                        category:"Food 2",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/food2/pop-corn.jpg",
                        title: "Pop-corn",
                        translate:"Поп-корн",
                        audio:"assets/audio/pop-corn.mp3",
                        category:"Food 2",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/food2/potatoes.jpg",
                        title: "Potatoes",
                        translate:"Картошечка",
                        audio:"assets/audio/potatoes.mp3",
                        category:"Food 2",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/food2/salat.png",
                        title: "Salad",
                        translate:"Салат",
                        audio:"assets/audio/salad.mp3",
                        category:"Food 2",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                ]
            },
            {
                picture: "assets/images/mainPage/jobs.jpg",
                title: "Jobs",
                cards: [
                    {
                        picture: "assets/images/jobs/builder.jpg",
                        title: "Builder",
                        translate:"Строитель",
                        audio:"assets/audio/builder.mp3",
                        category:"Jobs",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/jobs/cooker.jpg",
                        title: "Cooker",
                        translate:"Повар",
                        audio:"assets/audio/coocker.mp3",
                        category:"Jobs",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/jobs/cosmonaft.jpg",
                        title: "Cosmonaut",
                        translate:"Космонавт",
                        audio:"assets/audio/cosmonaut.mp3",
                        category:"Jobs",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/jobs/doctor.webp",
                        title: "Doctor",
                        translate:"Доктор",
                        audio:"assets/audio/doctor.mp3",
                        category:"Jobs",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/jobs/fireman.jpg",
                        title: "Fireman",
                        translate:"Пожарный",
                        audio:"assets/audio/fireman.mp3",
                        category:"Jobs",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/jobs/plumber.jpg",
                        title: "Plumber",
                        translate:"Сантехник",
                        audio:"assets/audio/plumber.mp3",
                        category:"Jobs",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/jobs/postman.jpg",
                        title: "Postman",
                        translate:"Почтальон",
                        audio:"assets/audio/postman.mp3",
                        category:"Jobs",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/jobs/teacher.jpg",
                        title: "Teacher",
                        translate:"Учитель",
                        audio:"assets/audio/teacher.mp3",
                        category:"Jobs",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                ]
            },
            {
                picture: "assets/images/mainPage/sport.jpg",
                title: "Sport",
                cards: [
                    {
                        picture: "assets/images/sport/backetball.png",
                        title: "Basketball",
                        translate:"Баскетбол",
                        audio:"assets/audio/basketball.mp3",
                        category:"Sport",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/sport/beisball.gif",
                        title: "Baseball",
                        translate:"Бейсбол",
                        audio:"assets/audio/baseball.mp3",
                        category:"Sport",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/sport/bodybuilder.jpg",
                        title: "Bodybuilding",
                        translate:"Бодибилдинг",
                        audio:"assets/audio/bodybuilding.mp3",
                        category:"Sport",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/sport/box.png",
                        title: "Boxing",
                        translate:"Бокс",
                        audio:"assets/audio/boxing.mp3",
                        category:"Sport",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/sport/football.gif",
                        title: "Football",
                        translate:"Футбол",
                        audio:"assets/audio/football.mp3",
                        category:"Sport",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/sport/runner.jpg",
                        title: "Running",
                        translate:"Бег",
                        audio:"assets/audio/running.mp3",
                        category:"Sport",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/sport/sky.jpg",
                        title: "Sky",
                        translate:"Лыжный спорт",
                        audio:"assets/audio/sky.mp3",
                        category:"Sport",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                    {
                        picture: "assets/images/sport/tennis.gif",
                        title: "Tennis",
                        translate:"Теннис",
                        audio:"assets/audio/tennis.mp3",
                        category:"Sport",
                        correct:0,
                        mistakes:0,
                        training:0,
                    },
                ]
            },
        ];
        if(!localStorage.getItem("score")){
            localStorage.setItem("score",JSON.stringify(this.cardsList))
        }
    }

    getCards(title) {
        return this.cardsList.find(item => item.title === title).cards;
    }

    getMain() {
        return this.cardsList;
    }

}